services:
  backend-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: backend-dev
    volumes:
      - .:/app 
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["entrypoints/uvicorn.sh"]

  db:
    container_name: db
    hostname: db
    image: library/postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app_dev
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  redis:
    container_name: redis
    image: bitnami/redis:7.4.1
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    volumes:  
      - redis_data:/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - db 
    ports:
      - "8080:8080"
      
volumes:
  redis_data:
  app_db_data:
    driver: "local"


