name: development-back
services:
  fastapi-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fastapi-dev 
    volumes:
      - ./app/:/app/app
      - ./alembic:/app/alembic
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    hostname: db
    image: library/postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-test:
    container_name: db-test
    image: library/postgres:16.3
    environment: 
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - 5433:5432
    restart: always

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - db 
    ports:
      - "8081:8080"
      
volumes:
  app_db_data:
    driver: "local"


