name: development-back
services:
  fastapi-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fastapi-dev 
    volumes:
      - ./app/:/app/app
      - ./alembic:/app/alembic
      - .env.dev:/app/.env
    ports:
      - "8001:8000"
    depends_on:
      - db
    entrypoint: ["entrypoints/uvicorn.sh"]

  db:
    container_name: db
    hostname: db
    image: library/postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - db 
    ports:
      - "8081:8080"
      
volumes:
  app_db_data:
    driver: "local"


