name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml  # Reuses your existing lint workflow

  test:
    uses: ./.github/workflows/tests.yml  # Reuses your existing test workflow

  build-and-push:
    needs: [lint, test]  # Only runs if linting and tests pass
    runs-on: ubuntu-20.04
    steps:

    - name: Cancel Previous Redundant Builds
      uses: styfle/cancel-workflow-action@0.11.0

    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    # DOcker images check
    # ALembic migrations
    # Backup
    # Push images to docker hub
    # Deploy to environment
