name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Migrate DB
      run: uv run alembic upgrade head
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        FIRST_SUPERUSER: test@test.com
        FIRST_SUPERUSER_PASSWORD: testpassword

    - name: Run Tests
      run: uv run --frozen pytest # Tests on PRs
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db



